In [1]:
import numpy as np

In [4]:
# 2차원 배열
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
# 1차원 배열
arr.reshape(12)
arr.reshape(3*4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
# flatten / ravel : 다차원 배열을 1차원 배열 변환 
#                  사용빈도가 빈번하여 기억하는게 좋음
arr.flatten()
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
# x는 1차원 배열 _ []가 1개있음
x = np.arange(3)
x

array([0, 1, 2])

In [11]:
# x는 2차원 배열(행렬, 1행*3열) _ []가 2개있음
x.reshape(1,3)

array([[0, 1, 2]])

In [12]:
# x는 2차원 배열(행렬, 3행*1열) _ []가 2개있음
x.reshape(3,1)

array([[0],
       [1],
       [2]])

In [13]:
x = np.arange(3)
x

array([0, 1, 2])

In [16]:
# newaxis : 차원 1씩 증가 함
# 2차원 배열(3행 1열)
x[ : , np.newaxis ]
x[ : , np.newaxis ].shape # (3, 1) 출력

(3, 1)

In [20]:
arr = arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
# for문 사용 가능
for i in arr:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [24]:
# 2차원 배열
arr = arr.reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
# 2차원 배열은 2중for문 사용
for i in arr:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [26]:
# 2중 for문
for i in arr:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [29]:
# 3차원배열
arr = arr.reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [31]:
# 3차원 배열은 3중 for문 사용
for i in arr:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [32]:
# 데이터 자료구조
# 파이썬 : 리스트, 튜플, 딕셔너리,집합
# 넘파이 : 배열(ndarray)
# 판다스 : 데이터 프레임, 시리즈

# 데이터 수집(크롤링, db) -> 전처리(넘파이 / 판다스) -> 분석(판다스)

In [45]:
# hstack()함수를 위한 소스
a1 = np.ones((2,3))
a2 = np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [40]:
# hstack()함수 : 2개의 행열을 수평(좌우)으로 합치는 함수
#               행이 일치되어야 가능하다.
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [43]:
# vstack()함수를 위한 소스
a1 = np.ones((2,3))
a2 = np.zeros((3,3))

In [44]:
# vstack()함수 : 2개의 행열을 수직(상하)으로 합치는 함수
#               열이 일치되어야 가능하다.
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
# dstack(depth) : 행과 열이 아닌 깊이 방향으로 배열을 합침(쉽게 생각하면 차원이 늘어나는 것)

In [47]:
a1 = np.ones((3,4))
a2 = np.zeros((3,4))

In [48]:
a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
# 2행 3열 4가 아닌
# 3 4행 2열로 변환됨
np.dstack([a1,a2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [52]:
np.dstack([a1,a2]).shape
# dstack([a1,a2]) => 2개의 3*4 배열 => 1개의 3*4*2 배열
# dstack은 잘 사용하지 않으며, stack을 주로 사용함

(3, 4, 2)

In [53]:
# stack()함수 : dstack보다 사용도가 많다
np.stack([a1,a2]) # axis(축)를 지정, 기본값 0
#2개 3*4 => 1개의 2*3*4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
#axis로 축 지정하는 법
r1 = np.stack([a1,a2],axis = 1)
r1

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [55]:
# 배열 확인
r1.shape #(3, 2, 4)

(3, 2, 4)

In [56]:
r2 = np.stack([a1,a2],axis = 2)
r2

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [57]:
# 배열 확인
r2.shape # (3, 4, 2)

(3, 4, 2)

In [58]:
# 두 행렬(3,4),(3,4)를 stack함수로 연결할 때 axis값에 따라 shape이 달라짐
# axis0 => 2,3,4
# axis1 => 3,2,4
# axis2 => 3,4,2

In [61]:
# 중간점검
# array([ 1,  2,  3, 11, 12, 13]) 출력해 보기
a1 = np.array([1,2,3])
a2 = np.array([11,12,13])
np.hstack([a1,a2])

array([ 1,  2,  3, 11, 12, 13])

In [62]:
# r_[] : hstack과 비슷한 결과 값 나옴
#        특별한 함수, 인덱서함수, r(row)
np.r_[a1,a2]
# 결과 : array([ 1,  2,  3, 11, 12, 13])

array([ 1,  2,  3, 11, 12, 13])

In [63]:
# c_[] : 특별한 함수, 인덱서함수, c(column)
np.c_[a1,a2]
# 결과 값
# array([[ 1, 11],
#        [ 2, 12],
#        [ 3, 13]])

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [64]:
# c_[]함수와 vstack 결과 값 비교
a1 = np.array([1,2,3])
a2 = np.array([11,12,13])
np.vstack([a1,a2])

# array([[ 1,  2,  3],
#        [11, 12, 13]])

array([[ 1,  2,  3],
       [11, 12, 13]])

In [67]:
# tile : 동일한 배열을 반복해서 연결 / 사용 빈도 적음
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
# tile함수 잘못된 형식 : 반복 숫자가 없어서 오류 발생
np.tile(arr)

TypeError: tile() missing 1 required positional argument: 'reps'

In [69]:
# tile함수 옳은 형식들
np.tile(arr, 3) # 좌우 방향으로 3번 반복 

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [70]:
np.tile(arr,(3,1)) # 위아래로 3번 반복, 좌우 방향으로 1번 반복

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [71]:
np.tile(arr,(3,2)) # 위아래로 3번 반복, 좌우 방향으로 2번 반복

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [73]:
# 중간 점검
# 아래와 같이 출력 하시오
# [[0., 0., 0., 1., 1.],
#  [0., 0., 0., 1., 1.],
#  [0., 0., 0., 1., 1.]]

# 첫번째 방식
arr = np.array([0,0,0,1,1])
np.tile(arr,(3,1))

#두번째 방식
arr1=np.ones((3,2))
arr2=np.zeros((3,3))
np.hstack([arr2,arr1])

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [74]:
# meshgrid() 함수 : 사각형의 영역을 출력
x = np.arange(3)
y = np.arange(5)
# (x,y) = (0,0),(0,1)...(0,4),(1,0)...(1,4)...(2,4)

In [75]:
x

array([0, 1, 2])

In [76]:
y

array([0, 1, 2, 3, 4])

In [78]:
x,y = np.meshgrid(x,y)

In [79]:
x

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [80]:
y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [81]:
# (x,y) = (0,0),(0,1)...(0,4),(1,0)...(1,4)...(2,4)

In [82]:
[list(zip(x,y)) for x,y in zip(x,y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [83]:
#concatenate 함수 : 하나로 합치는 합수
arr1 = np.array([1,2,3])
arr2 = np.array([11,21,31])

In [84]:
# 인수 1개있어애하며 [] 혹은 ()로 사용해야한다.
np.concatenate((arr1,arr2))

array([ 1,  2,  3, 11, 21, 31])

In [92]:
# 중간점검
# 아래 같이 출력하시오.
# array([[0,1,2,3,4,5],
#        [10,11,12,13,14,15],
#        [20,21,22,23,24,25],
#        [30,31,32,33,34,35],
#        [40,41,42,43,44,45],
#        [50,51,52,53,54,55]])

# 1
arr1 = np.arange(6)
arr2 = np.arange(0, 56, 10)

x = arr1 + arr2[:, np.newaxis]
x

# 2
arr1 = np.arange(6)
arr2 = np.arange(0, 51, 10)
n, m = np.meshgrid(arr1, arr2)
m + n

# 3
arr = np.arange(6)
res = arr
for i in range(5):
    new_arr = res + 10
    res = np.vstack([arr, new_arr])
res

# 4
arr = np.arange(6)
res = arr
for i in range(5):
    new_arr = res + 10
    res = np.vstack([arr, new_arr])
res

# 5
arrays = []
for i in range(6):
    arr = np.arange(0 + i * 10, 6 + i * 10)
    arrays.append(arr)

res = np.concatenate(arrays)
res.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [103]:
a=np.arange(1,5)
b=np.array([4,2,2,4,])

In [104]:
a

array([1, 2, 3, 4])

In [105]:
b

array([4, 2, 2, 4])

In [106]:
# 비교연산
a >= b
# array([False,  True,  True,  True]) 출력

array([False,  True,  True,  True])

In [107]:
# np.all(x <>= y)
# 각요소들을 일일이 비교하는게 아니라, 배열의 모든 요소에 대해 조건을 비교
np.all(a >= b) 

False

In [113]:
#벡터(행렬)끼리 연산하려면 크기가 동일해야 함
# 브로드캐스팅: 백터(행렬)의 크기가 다르더라도 연산이 가능하도록
# 크기를 동일하게 해주는 작업

# 예시
# 벡터        스칼라
# 1          10(분신)    11
# 2      +   10       = 12
# 3          10(분신)    13
# 4          10(분신)    14

In [114]:
x = np.arange(1,5)
x

array([1, 2, 3, 4])

In [115]:
y = 10

In [116]:
y

10

In [112]:
x + y

array([11, 12, 13, 14])

In [ ]:
행렬(2)       백터(1차원)->행열(2차원) 변경
             원래 백터 숫자 | 원래 없는 숫자
0 1 2        10(본체)     | 10(분신) 10(분신)
1 2 3    +   11(본체)     | 11(분신) 11(분신)
3 4 5        12(본체)     | 12(분신) 12(분신)
여기에서는 열 방향으로 증가함

In [ ]:
행렬(2)       백터(1차원)->행열(2차원) 변경
             
0 1 2        [10 11 12] (분신)
1 2 3    +   [10 11 12] (본체)
3 4 5        [10 11 12] (분신)
여기에서는 행 방향으로 증가함

In [120]:
x = np.arange(5)
y=1
x+y

array([1, 2, 3, 4, 5])

In [121]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [122]:
x

array([0, 1, 2, 3, 4])

In [123]:
x+y

array([1, 2, 3, 4, 5])

In [132]:
# array([[0,1,2],
#        [1,2,3],
#        [2,3,4],
#        [3,4,5],
#        [4,5,6]])

# 1
x = np.arange(3)
y = np.tile(x, (5, 1)) + np.arange(5)[:, np.newaxis]
y

# 2
x=np.arange(3)
y=np.arange(5)
x,y=np.meshgrid(x,y)
x+y

# 3
x, y = np.arange(3), np.arange(5)
x, y = np.meshgrid(x, y)
x + y

# 4
x = np.arange(3)
y = np.array([[0],[1],[2],[3],[4]])
x+y

# 5
arr=np.arange(3)
arr_f= [arr + i for i in range(5)]
arr_f=np.array(arr_f)
arr_f

# 6
x,y=np.meshgrid(np.arange(3),np.arange(5))
x+y

# 7
np.vstack([range(7)[i : i+3] for i in range(5)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])