In [1]:
import numpy as np

In [2]:
arr= np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
# 역순 출력
arr[::-1]

array([4, 3, 2, 1, 0])

In [5]:
# flip 함수 : 역순으로 출력
np.flip(arr)

array([4, 3, 2, 1, 0])

In [9]:
arr2d = np.arange(30).reshape(6,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [10]:
# 2차원 행만 뒤집짐
arr2d[::-1]

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [12]:
# 2차원 flip
np.flip(arr2d) #default(axis 지정 안함) : 행과 열 방향으로 뒤집기

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [13]:
# 열뒤집기
arr2d[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [14]:
# 열과 행 뒤집기
arr2d[:,::-1][::-1]

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [15]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [16]:
np.flip(arr2d,axis = 0) # axis(축) / axes(모든 축)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/IPython/core/inputtransformer2.py:627: UserWarning: `make_tokens_by_line` received a list of lines which do not have lineending markers ('\n', '\r', '\r\n', '\x0b', '\x0c'), behavior will be unspecified
  tokens_by_line = make_tokens_by_line(lines)


array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [18]:
np.flip(arr2d, axis = 1) # axis(축) / axes(모든 축) / axis=1(열 방향 뒤집기)

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [19]:
arr2d[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [20]:
np.flip(arr2d, axis=1)

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [26]:
# 5월 8일 문제 중
arr1 = np.zeros([3,3])
arr2 = np.ones([3,2])
arr12 = np.hstack([arr1,arr2])
arr12

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [29]:
arr3 = np.arange(10,151,10).reshape(3,-1)
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [32]:
arr_v = np.vstack([arr12,arr3])
arr_v

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [33]:
np.vstack([arr_v,arr_v])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [35]:
# tile 함수 사용하여 풀이
arr1=np.zeros([3])
arr2=np.ones([2])
arr12=np.hstack([arr1,arr2])
arr12

array([0., 0., 0., 1., 1.])

In [36]:
arr12_tile = np.tile(arr12,(3,1))
arr12_tile

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [39]:
arr3 = np.linspace(10,150,15).reshape(3,-1)
arr3

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [40]:
arr123 = np.vstack([arr12_tile,arr3])
arr123

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [42]:
res=np.tile(arr123, (2,1))
res

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [44]:
arr=np.arange(10,15)
arr

array([10, 11, 12, 13, 14])

In [45]:
# 합 / 스칼라이므로 0차원
np.sum(arr) # arr.sum() 같은 결과 나옴

60

In [47]:
# 최소값 / 스칼라이므로 0차원
np.min(arr) # arr.min()

10

In [48]:
# 최대값 / 스칼라이므로 0차원
np.max(arr) # arr.max()

14

In [50]:
# 2차원 배열 sum, min, max
arr  = np.arange(11,21).reshape(2,-1)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [54]:
np.sum(arr)
arr.sum()
np.min(arr)
np.max(arr)

20

In [56]:
# argmin() / argmax()함수 : 최소값 / 최대값 위치를 리턴하는 함수
arr.argmin() # 0 출력
arr.argmax() # 9 출력

9

In [58]:
arr[0].argmin() # 0출력
arr[0].argmax() # 4출력

4

In [60]:
# mean() 함수 : 평균값 구하는 함수
arr.mean() # 15.5 출력
arr[0].mean() # 13.0 출력

13.0

In [64]:
# 산술함수(평균)의 취약점
# 극단값에 영향이 받는다.
# 극단값을 영향을 많이 안 받고 대표값 구하는 게 좋다.
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [67]:
# arr.median() 사용불가
np.median(arr)
np.median(arr[0]) # 첫번째 줄의 중간 값

13.0

In [71]:
# all 함수
np.all(2>1) # 모두 다 True(참)인가? True or False
np.all([2>1, 5>3, 3<1])
np.all([2>1, 5>3, 3!=1])
np.all([True,True ,True])
np.all([True,True ,False])
# 하나라도 False 있으면 False 출력

False

In [72]:
# any 함수
np.any([True,True ,False]) # 하나라도 True 있으면 True 출력

True

In [75]:
np.all([1,2,3]) # True
np.all([1,2,0]) # False
np.all([1,2,0.1]) # True
# 0 : 거짓 / 0이 아니면 : 참

True

In [78]:
# 1차 배열 True / False 출력
np.all(np.arange(5)) # False / 0,1,2,3,4
np.all(np.arange(1,5)) # True / 1,2,3,4

True

In [80]:
a = np.zeros(10,dtype=np.int32)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [81]:
# 요소 하나하나씩 비교한다.
a == 0
# array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
#         True])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [82]:
np.all(a==0)
# True / 하나만 출력 된다.

True

In [83]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [84]:
# a에 저장된 값들이 모두 b에 저장된 값보다 작거나 같으면서
# b에 저장된 값들이 모두 c에 저장된 값보다 작거나 같은가요? True/False
np.all((a<=b) & (b <= c))

In [86]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
# 2차원 이상 다차원 배열에 대한 연산시에는 axis를 지정할 수 있음
# axis = 0(기본값, 열방량 연산), axis=1(행방향 연산)

In [89]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [92]:
arr.sum(axis=0) #열 단위로 합 구함
arr.sum(axis=1) #행 단위로 합 구함

array([10, 35])

In [93]:
arr.max(axis=0) #열 단위로 최대값
arr.max(axis=1) #행 단위로 최대값

array([5, 6, 7, 8, 9])

In [102]:
# 중간 점검
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [96]:
a.max(axis=1)

array([ 7, 12, 15])

In [98]:
# sort()함수 : 열 방향으로 올름차순으로 정렬
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [100]:
a.sort(axis=0)
a
# 출력값
# array([[ 1,  3,  1,  7],
#        [ 2, 12,  5,  9],
#        [ 4, 15, 11, 14]])

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [103]:
a.sort(axis=1)
a
# 출력값
# array([[ 3,  4,  5,  7],
#        [ 1,  9, 11, 12],
#        [ 1,  2, 14, 15]])

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [104]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])

In [105]:
np.sort(a) # axis 값이 1일때와 같음

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [106]:
arr = np.array([40,20,10,30,90])
arr

array([40, 20, 10, 30, 90])

In [107]:
# 올름차순
np.sort(arr)

array([10, 20, 30, 40, 90])

In [108]:
# 내림차순 1
np.sort(arr)[::-1]

array([90, 40, 30, 20, 10])

In [109]:
# 내림차순 2
np.flip(np.sort(arr))

array([90, 40, 30, 20, 10])

In [110]:
arr # 정렬해도 원래대로 된다. 이전에는 일시 적으로 저장

array([40, 20, 10, 30, 90])

In [111]:
# 완전히 저장이된다.
arr = np.sort(arr)[::-1]
arr

array([90, 40, 30, 20, 10])

In [113]:
arr.sort()

In [114]:
arr

array([10, 20, 30, 40, 90])

In [115]:
len(arr)

5

In [116]:
np.mean(arr)

38.0

In [117]:
# 분산
np.var(arr)

776.0

In [118]:
# 표준편차
np.std(arr)

27.85677655436824

In [132]:
# x에 대한 표준분산을 구하시오.
x = np.array([5,10,9,3,8])
x
# 1)
std_dev_x = np.sum((x - np.mean(x)) ** 2) / (len(x) - 1)
std_dev_x

# 2)
np.sum(((x-x.mean())**2))/(len(x)-1)

8.5

In [134]:
# 모본 분산
x = np.array([5, 10, 9, 3, 8])
variance_x = np.var(x)

print("모본 분산:", variance_x)

표준 분산: 6.8


In [141]:
np.var(x) #6.8
np.sum((x - np.mean(x))**2)/(len(x))
np.var(x, ddof=1) # 표본분산 / 8.5

8.5

In [143]:
x = np.arange(1,201)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [ ]:
# 백분위수 : 위치를 100으로 나눈 수

In [145]:
np.percentile(x,0) # 최소값

1.0

In [146]:
np.percentile(x,100) # 최대값

200.0

In [153]:
# 1사분위수 : 25% 백분율
np.percentile(x,25)

50.75

In [154]:
# 2사분위수 : 50% 백분율
np.percentile(x,50)

100.5

In [155]:
# 3사분위수 : 75% 백분율
np.percentile(x,75)

150.25

In [156]:
# 4사분위수 : 100% 백분율
np.percentile(x,100)

200.0

In [158]:
data=np.arange(11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

5.0

In [160]:
np.percentile(data,25) # 1사분위

2.5

In [161]:
np.percentile(data,50) #중위수(2사분위)

5.0

In [162]:
np.percentile(data,75) # 3사분위

7.5

In [163]:
np.percentile(data,100) # 4사분위 / 최대

10.0

In [2]:
import numpy as np

In [62]:
# 1. 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
arr = np.arange(1,31).reshape(5,6)
arr
# 전체의 최댓값
arr.max()

# 각 행의 합
arr.sum(axis=1)

# 각 행의 최댓값
arr.max(axis = 1)

# 각 열의 평균
arr.mean(axis = 0)

# 각 열의 최솟값
arr.min(axis = 0)

array([1, 2, 3, 4, 5, 6])

In [78]:
# 2. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.

score = np.array([[  1,    2,    3,    4],
                  [ 46,   99,  100,   71],
                  [ 81,   59,   90,  100]])

# 영어 점수로 정렬된 인덱스 가져오기
eng_sorted_indices = np.argsort(score[1])

# 영어 점수로 정렬된 배열 생성
sorted_score = score[:, eng_sorted_indices]

print(sorted_score)

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [58]:
# 5월 8일 미 해결 문제
# 1. 지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 다양한 방법으로 만드시오.
# - tile사용, tile 미사용,...
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

# 1-1 tile 사용
arr0 = np.zeros([3])
arr1 = np.ones([2])
arrhap = np.hstack([arr0,arr1]) # array([0., 0., 0., 1., 1.])
arrhap_tile = np.tile(arrhap,(3,1))

arr2 = np.linspace(10,150,15).reshape(3,-1)

arr012 = np.vstack([arrhap_tile,arr2])
arr012

# 1-2 tile 미사용
arr1 = np.hstack([np.zeros((12, 3)), np.ones((12, 2))])
arr2 = np.arange(10, 151, 10).reshape(3, 5)

arr1[3:6, :], arr1[9:12, :] = arr2, arr2

arr1

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [77]:
# 2.  아래와 같은 구조의 배열을 생성하시오
# 1 2 3 4 5
# 10 9 8 7 6
# 11 12 13 14 15
# 20 19 18 17 16
# 21 22 23 24 25

arr = np.arange(1, 26).reshape(5, -1)

arr[1::2, :] = np.flip(arr[1::2, :], axis=1)

print(arr)

[[ 1  2  3  4  5]
 [10  9  8  7  6]
 [11 12 13 14 15]
 [20 19 18 17 16]
 [21 22 23 24 25]]
