In [5]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
arr.dtype # 데이터 타입 / dtype('int64')출력 됨 int타입이고 64bit이다.

dtype('int64')

In [10]:
type(arr) 
# arr 안에 있는 형식의 타입이 나온다.
# numpy.ndarray 출력_배열이기 때문에 int가 출력이 안나오고 numpy.ndarray이 나온다

numpy.ndarray

In [11]:
type(arr[0]) # numpy.int64 출력

numpy.int64

In [ ]:
1MB = 100만 바이트
1GB = 10억 바이트
32GB = 320억 바이트
320억 / 4 = 80억개 정수를 저장

In [12]:
arr = np.array(['APPLE','CHERRY','BANNA'])
arr.dtype
# dtype('<U6') 출력
# U의 의미는 unicod의미하며 영어권뿐만 아니라 모든언어에 대한 체계
# 숫자 6은 최대 문자 길이를 나타낸다

dtype('<U6')

In [18]:
arr = np.array([1,2,3], dtype = np.float64)
arr.dtype
# dtype('float64') 출력

dtype('float64')

In [19]:
arr = np.array([1,2,3], dtype = np.float16)
arr.dtype
#dtype('float16') 출력

dtype('float16')

In [21]:
arr = np.array([1,2,3], dtype = np.int64)
arr.dtype
# dtype('int64') 출력

dtype('int64')

In [23]:
arr = np.array([1,2,3], dtype = np.int16)
arr.dtype
#dtype('int16') 출력

dtype('int16')

In [24]:
arr = np.array([1,2,3], dtype = np.float64)
arr.dtype
# 64비트 float 수의 범위 = 4.9 *10의  324승~1.79*10의 308승
# 32비트 float 수의 범위 = 1.9 *10의  45승~3.4*10의 38승

# 32비트 int 수의 범위 = -21억~+21억
# 64비트 int 수의 범위 = -922경~+922경

# 넓은 범위에 수를 다루고 싶으면 int보다 float을 사용하는 것을 추천
# 

dtype('float64')

In [25]:
arr # array([1., 2., 3.]) 출력

array([1., 2., 3.])

In [27]:
arr = np.array([1,2,3], dtype = 'i1') # i 바이트 수
arr
# array([1, 2, 3], dtype=int8) 출력

array([1, 2, 3], dtype=int8)

In [29]:
arr = np.array([1,2,3], dtype = 'i2') # i 바이트 수
arr
# array([1, 2, 3], dtype=int6) 출력

array([1, 2, 3], dtype=int16)

In [31]:
arr = np.array([1,2,3])
arr
arr.dtype

dtype('int64')

In [32]:
# astype을 사용하여 타입 변경 가능
farr = arr.astype(np.float32)
farr
#array([1., 2., 3.], dtype=float32) 출력 dot(.) 붙혀서 출력 됨

array([1., 2., 3.], dtype=float32)

In [34]:
farr2 = np.array([1,2,3,], dtype = np.float32)
farr2 # array([1., 2., 3.], dtype=float32) 출력

'''
상황에 맞게 astype 및 np.array([1,2,3,], dtype = np.float32) 사용한다.
'''

array([1., 2., 3.], dtype=float32)

In [35]:
arr = np.array([1,2,3,])
arr

array([1, 2, 3])

In [37]:
myList = [1,2,'3']
myList

[1, 2, '3']

In [39]:
type(myList) #list
type(myList[0]) # int
type(myList[2]) # str

int

In [40]:
imyList = [1,2,3]
cmyList = [1,2,'3']

In [41]:
np.array(imyList)
# array([1, 2, 3]) 출력

array([1, 2, 3])

In [42]:
np.array(cmyList)
# array(['1', '2', '3'], dtype='<U21') 출력
# 일괄적으로 문자열로 변경 됨
# 배열 : 동일한 타입(크기도 같고)의 데이터를 여러개 나열한 것

array(['1', '2', '3'], dtype='<U21')

In [43]:
arr1 = np.array(list(range(10,14))).reshape(2,2)
arr2 = np.array(list(range(10,14))).reshape(2,2)

In [44]:
arr1
arr2
#array([[10, 11],
#      [12, 13]])

array([[10, 11],
       [12, 13]])

In [45]:
arr1-arr2
#array([[0, 0],
#      [0, 0]])

array([[0, 0],
       [0, 0]])

In [46]:
arr1*2 #숫자와 연산을 할때는 모든 항목에 동일한 연산
#array([[20, 22],
#      [24, 26]])

array([[20, 22],
       [24, 26]])

In [47]:
arr1*arr2 # 주의 : 행렬의 곱셈(mtrix mutiply,matmul)이 아님
#요소간 곱셈(element-wise product)
#array([[100, 121],
#      [144, 169]])

array([[100, 121],
       [144, 169]])

In [48]:
arr1=np.array(list(range(10,14))).reshape(2,2)
arr1

array([[10, 11],
       [12, 13]])

In [49]:
arr2=np.array(list(range(13,17))).reshape(2,2)
arr2

array([[13, 14],
       [15, 16]])

In [50]:
# 사칙연산뿐만 아니라 비교연산 가능
arr1>arr2
#array([[False, False],
#      [False, False]])

array([[False, False],
       [False, False]])

In [51]:
arr1<arr2
#array([[ True,  True],
#      [ True,  True]])

array([[ True,  True],
       [ True,  True]])

In [52]:
~(arr1 == arr2) # ~는 not 연산자
# array([[ True,  True],
#      [ True,  True]])

array([[ True,  True],
       [ True,  True]])

In [53]:
arr1!= arr2 #같지않다 !=
#array([[ True,  True],
#      [ True,  True]])

array([[ True,  True],
       [ True,  True]])

In [55]:
~(arr1 != arr2)
# array([[False, False],
#      [False, False]])

array([[False, False],
       [False, False]])

In [54]:
(~(arr1 == arr2) | ~(arr1 != arr2))
#                OR
#OR 연선저는 둘 중 하나 이상이 TRUE면 TRUE 출력

array([[ True,  True],
       [ True,  True]])

In [56]:
# arange는 배열 만들 때 쉽게 만들 수 있음
np.arange(8) #np.array(list(range(8))와 같은 코드

array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [62]:
#1-24까지의 값,2*3*4 행렬
# arange / array 2가지를 사용하여 만들기

np.arange(1,25).reshape(2,3,4)
np.array(list(range(1,25))).reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [63]:
data = np.arange(200)
data
data2 = data.reshape(4,-1)
data2.shape # (4, 50) 출력

(4, 50)

In [67]:
data3 = data.reshape(6,-1)
data3 # Error 출력
      # ValueError: cannot reshape array of size 200 into shape (6,newaxis)
      # 6의 약수가 아니라서 Error가 출력됨

ValueError: cannot reshape array of size 200 into shape (6,newaxis)

In [68]:
data4 = data.reshape(-1,10)
data4

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [71]:
data.reshape(-1,5,10) # 4*5*10 배열로 출력
data.reshape(4,-1,10) # 4*5*10 배열로 출력

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]],

       [[150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 

In [74]:
# 2차원 배열 생성
# 10부터 시작하여 2씩 증가시켜 값으로 초기화
# shape은 3행 4열
np.arange(10,34,2).reshape(3,4)
np.array(list(range(10,34,2))).reshape(3,4)

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [76]:
np.arange(10,34,2).reshape(3,4)

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [79]:
# 불린참조(팬시)
# 사용 빈도 많으므로 자세히 알고 있으면 유용하다.

arr = np.array([1,2,3,4]) #데이터 저장된 배열
idx = np.array([True,False,False,True]) # 불린 저장된 배열

In [80]:
arr[idx] # array([1, 4]) 출력
# True 대응하는 값만 출력된다.

array([1, 4])

In [83]:
arr = np.array([1,2,3,4]) #데이터 저장된 배열
idx = np.array([True,True,False,False,True]) # 불린 저장된 배열
arr[idx] # Error
# 갯수가 다르므로 Error가 나옴

IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 5

In [84]:
np.min(arr) # 최소값인 1 출력
np.max(arr) # 최댓값인 4 출력

1

In [88]:
arr == 1
# array([ True, False, False, False]) 출력

array([ True, False, False, False])

In [91]:
arr == 4
# array([False, False, False,  True]) 출력

array([False, False, False,  True])

In [89]:
#python List 버전
myList = [1,2,3,4]
for i in myList:
    if i ==1:
        print(True)
    else:
        print(False)
# 불필요하게 길게 할 필요가 없고 불린참조 사용

True
False
False
False


In [93]:
(arr == np.min(arr)) | (arr == np.max(arr))
# array([ True, False, False,  True]) 출력

array([ True, False, False,  True])

In [94]:
arr[(arr == np.min(arr)) | (arr == np.max(arr))]
# array([1, 4]) 출력

array([1, 4])

In [97]:
# 11~20까지의 수가 저장된 배열 arr 생성
arr = np.arange(11,21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [98]:
arr % 2
# 2를 나눈 나머지 출력
# array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) 출력

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [99]:
arr % 2 == 0
# 2를 나눠서 0이면 True 아니면 False 출력
# array([False,  True, False,  True, False,  True, False,  True, False, True]) 출력

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [100]:
arr[arr % 2 == 0]
# 2를 나눈 수중 0이 나오는 수만 출력
# array([12, 14, 16, 18, 20]) 출력

array([12, 14, 16, 18, 20])

In [101]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [106]:
arr[1]

arr[1,3] # Error 나옴 / Error내용 : IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
         # 배열은 1차원인데 출력하고자하는 코드는 2차원이라 Error 나옴

arr[np.array([1,3])] # 위 코드는 틀린 코드이고 현위치의 코드는 옳은 코드이다
                     # array([12, 14]) 출력

# 추후 출력해 보기
arr[np.array([1,3,5,7,9])]
arr[np.array([1,3,5,7,9,9,9,9,9,9])]

array([12, 14])

In [107]:
idx = np.array([0,0,0,1,1,1,3,3,3,])

In [108]:
arr[idx] # array([11, 11, 11, 12, 12, 12, 14, 14, 14]) 출력

array([11, 11, 11, 12, 12, 12, 14, 14, 14])

In [109]:
arr = np.arange(10,40).reshape(5,-1)
arr

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [112]:
arr[:] # 전체행 출력
arr[:,:] #전체행에 대해 전체열을 추출

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [113]:
arr[:,[True,True,True,False,False,False]] # 아래와 같이 출력 됨 
# array([[10, 11, 12],
#        [16, 17, 18],
#        [22, 23, 24],
#        [28, 29, 30],
#        [34, 35, 36]])

array([[10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])

In [116]:
# 위에 코드와 같은 결과인데 다른 버전의 코드
idx = np.array([True,True,True,False,False,False])
idx
arr[:,idx]

array([[10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])

In [120]:
#arr에서 1(10~),3(12~),5(14~)번째 열을 출력하시오.
arr[:, idx]
arr[:, [0, 2, 4]]
arr[:, np.array([0, 2, 4])]
arr[:, np.arange(0, 5, 2)]
#4가지 코드는 동일한 결과가 출력됨

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [122]:
arr[:,[4,1,3,0]] # 순서를 바뀜
# array([[14, 11, 13, 10],
#        [20, 17, 19, 16],
#        [26, 23, 25, 22],
#        [32, 29, 31, 28],
#        [38, 35, 37, 34]])

array([[14, 11, 13, 10],
       [20, 17, 19, 16],
       [26, 23, 25, 22],
       [32, 29, 31, 28],
       [38, 35, 37, 34]])

In [124]:
# arr에서 3번째 행, 2번째 행, 4번째행 순서로 데이터를 출력하시오.
arr[[2,1,3]] # 헹과 열을 구분하는 컴마가 생략되었을 경우에는 행 추출
# array([[22, 23, 24, 25, 26, 27],
#        [16, 17, 18, 19, 20, 21],
#        [28, 29, 30, 31, 32, 33]])

array([[22, 23, 24, 25, 26, 27],
       [16, 17, 18, 19, 20, 21],
       [28, 29, 30, 31, 32, 33]])

In [ ]:
# arr[ 행 , 열 ]
# , 기준으로 좌측은 행, 우측은 열이다.
arr[:,[2,1,3]] # arr의 전체 행에서 [2,1,3]번 열을 추출

In [125]:
arr[[2,1,3],:]

array([[22, 23, 24, 25, 26, 27],
       [16, 17, 18, 19, 20, 21],
       [28, 29, 30, 31, 32, 33]])

In [126]:
# 무한대(infinity) : np.inf
# 숫자아님(not a number) : np.nan

In [128]:
np.array([1])/np.array([0]) # array([inf])출력
np.log(0) # -inf출력

/var/folders/bs/rn4q13z924s9_wzlq41h6grc0000gn/T/ipykernel_1356/618795488.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([1])/np.array([0]) # array([inf])출력
/var/folders/bs/rn4q13z924s9_wzlq41h6grc0000gn/T/ipykernel_1356/618795488.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [130]:
#0/0
np.array([0])/np.array([0]) # array([nan]) 출력

/var/folders/bs/rn4q13z924s9_wzlq41h6grc0000gn/T/ipykernel_1356/2748191917.py:2: RuntimeWarning: invalid value encountered in divide
  np.array([0])/np.array([0])


array([nan])

In [131]:
# zeros / ones는 사용빈도는 적지만 가끔 사용이 됨
np.zeros(3) # 모든 값이 0으로 만들고 3열로 배열 시킴
            # array([0., 0., 0.]) 출력

array([0., 0., 0.])

In [132]:
np.zeros((3,2))
# 결과
# array([[0., 0.],
#        [0., 0.],
#        [0., 0.]])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [133]:
np.zeros((3,2)).dtype
# 타입 : dtype('float64')

dtype('float64')

In [135]:
np.zeros((3,2),dtype='i')
np.zeros((3,2),dtype='i4')

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [136]:
np.zeros((3,2),dtype='i8')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [138]:
np.ones((3,2))
# 모든 숫자가 1로 초기화
# 결과
# array([[1., 1.],
#        [1., 1.],
#        [1., 1.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [140]:
np.twos((3,2))
# twos부터 나머지는 출력이 안나오고 zeros / ones만 출력 된다

AttributeError: module 'numpy' has no attribute 'twos'

In [141]:
# twos출력하고 싶으면 밑에 코드로 사용된다.
np.ones((3,2))*2

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [144]:
# np.ones_like 함수
# 사용빈도는 그나마 조금 있는 함수

In [145]:
np.ones_like(arr)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [146]:
np.zeros_like(arr)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [148]:
np.arange(2,31,2).reshape(-1,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [150]:
# linspace 함수 : 구간을 나누는 함수
# 사용 빈도 적은 함수
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [154]:
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
# transpase : 전치행렬(행과 열을 바꾼 행렬)
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [156]:
# transpose 2번 사용하면 원래 행렬이 된다
arr.transpose().transpose()

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
# (사과, 배, 딸기)
data = np.array([[1,5,0],
                [5,3,2],
                [1,2,0]])
price = np.array([[1000],
                  [5000],
                  [8000]])

In [160]:
data.shape # 3행 3열
price.shape # 3행 1열

(3, 1)

In [161]:
# data배열과 price배열간에 행렬의 곱셈 연산 가능하다
data.dot(price) #내적

array([[26000],
       [36000],
       [11000]])

In [163]:
# .dot()과 @ : 2차원에서는 결과값이 같음
data@(price) # 행렬의 곱셉
             # 3차원부터 결과값이 다라짐

array([[26000],
       [36000],
       [11000]])

In [177]:
arr = np.arange(10,15)
arr

array([10, 11, 12, 13, 14])

In [178]:
arr2 = arr # 데이터를 공유한다는 의미(뷰)
arr2[1] = 99
arr2

array([10, 99, 12, 13, 14])

In [179]:
arr

array([10, 99, 12, 13, 14])

In [173]:
# 여기는 copy 함수 사용함
arr = np.arange(10,15)
arr3 = arr.copy()
arr3

array([10, 11, 12, 13, 14])

In [175]:
arr3[1]=99
arr3

array([10, 99, 12, 13, 14])

In [176]:
arr

array([10, 11, 12, 13, 14])

In [181]:
# 1. 1차원 numpy 배열을 만들어 결과와 같이 출력하기
#[ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

arr = np.arange(0,29,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [188]:
# 2. 2차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[10, 20, 30, 40],
# 50, 60, 70, 80]]

np.arange(10,81,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [190]:
# 3. 3차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[[ 1, 2, 3],
# [ 4, 5, 6]],
# [[ 7, 8, 9],
# [10, 11, 12]],
# [[13, 14, 15],
# [16, 17, 18]],
# [[19, 20, 21],
# [22, 23, 24]]]

np.arange(1,25).reshape(2,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [197]:
# 4. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
# vector = np.array(range(0, 30, 2))

# 값 24 인덱싱
# 값 6 인덱싱

vector = np.array(range(0, 30, 2))
vector[-3]
vector[3]

6

In [208]:
# 5. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
matrix = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])

# 1)- 값 8 인덱싱
matrix[1,-1]

# 2)- 값 2 인덱싱
matrix[0,1]

# 3)- 값 9 인덱싱
matrix[2,0]

# 4)- 값 15 인덱싱
matrix[-1,-2]

15

In [210]:
# 6. 아래와 같은 행렬을 작성해보세요
# [-1, -2, -3, -4, -5]

np.arange(-1,-6,-1)

array([-1, -2, -3, -4, -5])

In [221]:
# 7.다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 1)이 배열에서 3의 배수를 찾아라.
print(x[x % 3 == 0])

# 2)이 배열에서 4로 나누면 1이 남는 수를 찾아라.
print(x[x % 4 == 1])

# 3)이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [237]:
# 8. 다음 배열을 만들고 슬라이싱, 인덱싱 연습하세요
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

# 1)
print(arr2d[1,1]) 
# 5

# 2)
print(arr2d[0]) 
# [1 2 3]

# 3)
print(arr2d[:,2]) 
# [3 6 9]

#4)
print(arr2d[:2, 1:])
#[[2 3]
#[5 6]]

# 5)
print(arr2d[0:2]) 
# [[1 2 3]
# [4 5 6]]

# 6)
print(arr2d[:,0:2]) 
# [[1 2]
#  [4 5]
#  [7 8]]

# 7)
print(arr2d[:,-1])
#[3 6 9]

# 8)
arr2d[:2, 1:] =0
print(arr2d)
# [[1 0 0]
#  [4 0 0]
#  [7 8 9]]

5
[1 2 3]
[3 6 9]
[[2 3]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]
[3 6 9]
[[1 0 0]
 [4 0 0]
 [7 8 9]]


In [ ]:
# 1) 특정 원소에 접근
print(arr2d[1,1]) # arr2d[행 인덱스, 열 인덱스]
# 5

# 2) 특정 행에 접근
print(arr2d[0]) # arr2d[행 인덱스]
# [1 2 3]

# 3) 특정 열에 접근
print(arr2d[:,2]) # arr2d[:, 열 인덱스]
# [3 6 9]

#4) 부분 배열(슬라이스) 생성
print(arr2d[:2, 1:]) # arr2d[시작 행:끝 행, 시작 열:끝 열]
#[[2 3]
#[5 6]]

# 5) 특정 행 범위에 접근
print(arr2d[0:2]) # arr2d[시작 행:끝 행]
# [[1 2 3]
# [4 5 6]]

# 6 특정 열 범위에 접근
print(arr2d[:,0:2])  # arr2d[:, 시작 열:끝 열]
# [[1 2]
#  [4 5]
#  [7 8]]

# 7) 마지막 열에 접근
print(arr2d[:,-1]) # arr2d[:, 음수 인덱스]
#[3 6 9]

# 8) 부분 배열에 새로운 값을 할당
arr2d[:2, 1:] =0 # arr2d[시작 행:끝 행, 시작 열:끝 열]
print(arr2d)
# [[1 0 0]
#  [4 0 0]
#  [7 8 9]]