In [1]:
import numpy as np

In [4]:
# 시드(seed)를 이용하여 난수 발생


TypeError: 'module' object is not callable

In [5]:
# 시드없이 랜덤 난수 발생
np.random.rand()

0.6489171859970306

In [11]:
# 시드 지정하여 출력
np.random.seed(20240510)
np.random.rand()
# 0.24432338459661196 출력

np.random.rand(10)
# 결과 값
# array([0.63551756, 0.67221731, 0.8370985 , 0.3230404 , 0.66728613,
#        0.99852928, 0.95145872, 0.36059922, 0.68687786, 0.21542222])

array([0.63551756, 0.67221731, 0.8370985 , 0.3230404 , 0.66728613,
       0.99852928, 0.95145872, 0.36059922, 0.68687786, 0.21542222])

In [18]:
x = np.arange(11,15)
x

array([11, 12, 13, 14])

In [19]:
# shuffle() 함수
np.random.shuffle(x)
x

array([13, 11, 14, 12])

In [21]:
# choice : 표본 추출 함수
np.random.choice()
# 에러 발생
# 에러 내용 
# TypeError: choice() takes at least 1 positional argument (0 given)

TypeError: choice() takes at least 1 positional argument (0 given)

In [22]:
np.random.choice(x)
# 에러 발생하지 않음

14

In [27]:
np.random.choice(5,3, p = [0.1,0,0.3,0.6,0])

array([3, 3, 3])

In [28]:
# np.random.rand() : 0<=난수<1 출력
# np.random.randn() : 표준정규분포(평균:0,표준편차:1)
# np.random.randint() : 균등분포, 정수 난수

In [29]:
np.random.rand(15)

array([0.28792406, 0.58950279, 0.93466037, 0.48068957, 0.97200741,
       0.42262745, 0.4429743 , 0.73293894, 0.29821515, 0.37816457,
       0.95099299, 0.03897989, 0.58617992, 0.12690682, 0.1489538 ])

In [39]:
# 따로 reshape 할 필요가 없다
np.random.rand(3,5)

array([[0.5595396 , 0.05808629, 0.39915812, 0.14356235, 0.05267766],
       [0.29529782, 0.24027168, 0.11996385, 0.70605489, 0.37044677],
       [0.34308801, 0.94277835, 0.13742611, 0.51585373, 0.79988064]])

In [40]:
np.random.randn(10)
np.mean(np.random.randn(10))
np.std(np.random.randn(10))

0.550466187246017

In [50]:
np.random.randint(1) # 0출력
np.random.randint(3) # 0-2 출력
np.random.randint(5,10) #5와 10사이 난수 출력
np.random.randint(5,10,size=10) # 5와 10사이 난수 10개 출력
np.random.randint(5,10,size=(2,5)) # 5와 10사이 난수 10개 출력하되 2행 5열로 출력

array([[7, 8, 5, 6, 6],
       [6, 6, 8, 9, 9]])

In [56]:
data=np.random.randint(5, 11, size=10)
data

array([ 6,  8,  7, 10,  5,  8, 10,  9,  7,  8])

In [68]:
# unique() 함수
np.unique(data) # array([5, 6, 7, 8, 9]) 출력

array([ 5,  6,  7,  8,  9, 10])

In [69]:
np.unique(data, return_counts=True)
# 결과 값
# (array([5, 6, 7, 8, 9]), array([1, 3, 3, 1, 2]))

(array([ 5,  6,  7,  8,  9, 10]), array([1, 1, 2, 3, 1, 2]))

In [70]:
np.unique(data, return_counts=True)[0]
np.unique(data, return_counts=True)[1]

array([1, 1, 2, 3, 1, 2])

In [72]:
np.bincount(data, minlength=11) 
#minlength: 0부터 설정된 값-1까지 수를 범위로 설정하여 빈도수 조사
#minlength=11 이면 0부터 10까지 수를 범위로 설정하여 빈도수 조사
#결과 : array([0, 0, 0, 0, 0, 3, 0, 1, 2, 1, 3], dtype=int64)
#              0 1  2   3  4  5  6  7  8  9  10

array([0, 0, 0, 0, 0, 1, 1, 2, 3, 1, 2])

In [73]:
data

array([ 6,  8,  7, 10,  5,  8, 10,  9,  7,  8])

In [75]:
# 로또 수 5개 출력
def generate_lotto_nums():
    return np.sort(np.random.choice(np.arange(1, 46), size=6, replace=False))

# 5줄을 출력하는 반복문
for _ in range(5):
    print(generate_lotto_nums())

# 동전을 10번 던져 앞면(숫자1)과 뒷면(숫자0)이 나오는 가상 실험을 파이썬으로 작성
np.random.choice(2, 10, p=[0.5, 0.5])

# 주사위를 100번 던져서 나오는 숫자의 평균을 구하라
random_num = np.random.randint(1, high=7, size=100)
np.mean(random_num)

3.52

[ 9 10 29 35 38 45]
[ 4  7 20 33 34 39]
[ 4 24 29 30 38 43]
[10 13 17 21 24 39]
[ 1  5 21 25 30 36]


In [106]:
1. 알고리즘을 평가하는 방법은?

1 . 코드복잡도
2 . 시간복잡도 V
3 . 세타복잡도
4 . 스몰복잡도
정답
2
해설
시간복잡도를 이용하여 알고리즘을 평가한다.

현재: 55
56


In [107]:
#2.다음 코드의 실행 결과에 출력되는 값은?
list = [1,3,0,4,2]
cnt = 0
index = 1
while index != 0:
    index = list[index]
    cnt = cnt + 1
print(cnt)

# 1 . 1
# 2 . 2
# 3 . 3
# 4 . 4 V
# 정답
# 4
# 해설
# list의 값을 index로 재사용하는 구조로 index는 최초 1부터 시작하여 1 → 3 → 4 → 2 로 변경되고 
# list[2]값이 0이므로 cnt가 4까지만 증가하고 반복문을 종료한다.

4


In [108]:
#3.다음 코드를 실행한 결과로 출력되는 값은?

def recursion(num):
    if num == 3:
        return
    recursion(num + 1)
    print(num, end=" ")

recursion(0)

# 힌트
# 1 . 2 0 0
# 2 . 2 1 0 v
# 3 . 2 2 0
# 4 . 2 3 0
# 정답
# 2
# 해설
# 최초에 run 함수에 0을 넣은 상태로 호출되나, 
# 내부에서 run 함수를 계속하여 재귀 호출한다.
# n이 3일때 리턴하므로 2 > 1 > 0 순으로 출력된다

2 1 0 

In [110]:
# 4.다음 코드를 실행한 결과로 출력되는 값은?
arr = [1,2,6,5,4,2]
dat = [0 for _ in range(len(arr) + 1)]

for i in range((len(arr))):
    dat[arr[i]] = 1

for i in range(len(dat)):
    if dat[i] == 0:
        continue

    print(i, end = " ")

# 1 . 1 2 3 4 5 6
# 2 . 1 2 4 5 6 v
# 3 . 1 3 4 5 6
# 4 . 2 3 4 5 6
# 정답
# 2
# 해설
# arr 배열에 존재하는 값을 dat 배열에 체크한 후, dat배열에 값이 존재하는 경우만 출력한다.

1 2 4 5 6 

In [111]:
# 5.다음 코드를 실행한 결과로 출력되는 값은?
str = "ABKRNW"
idx = [1, 3, 1, 3, 2]
result = ""

for i in range(len(idx)):
    result += str[idx[i]]

print(result)

# 1 . BRWNA
# 2 . BRBRN
# 3 . BRBRK v
# 4 . BRBRA
# 정답
# 3
# 해설
# 5번(idx의 크기) 만큼 result에 1,3,1,3,2 인덱스를 누적한다.
# 배열이 0번 인덱스부터 시작하는 것을 주의한다

BRBRK


In [114]:
# 6.다음 코드를 실행한 결과로 출력되는 값은?
arr = [[0 for _ in range(3)] for _ in range(3)]

t = 1

for i in range(2,-1,-1):
    for j in range(0,3):
        arr[j][i] = t

    t = t + 1

for i in range(0,3):
    print(arr[i][i], end=" ")

# 1 . 7 5 0
# 2 . 7 5 1
# 3 . 7 5 2
# 4 . 7 5 3 v
# 정답
# 4
# 해설
# 위 반복문을 실행하면 {{7,4,1},{8,5,2},{9,6,3}} 배열이 생성되고, 
# 아래 반복문에서 [0,0][1,1],[2,2]순으로 출력하여 753이 출력된다

3 2 1 

In [ ]:
7.다음 코드를 실행한 결과로 출력되는 값은?
arr = [[1, 1, 0, 1], [0, 1, 1, 0], [1, 1, 1, 0], [1, 1, 1, 1]]
cnt = 0

for i in range(1,3):
for j in range(2,4):
if(arr[i][j] == 1):
cnt = cnt + 1
for j in range(0, 3):
if (arr[i][j] == 1):
cnt = cnt + 1

print(cnt)

1 . 7 v
2 . 8
3 . 9
4 . 10
정답
1
해설
이차원 배열안에 존재하는 값을 체크하면서 cnt에 누적한 값을 출력한다

In [ ]:
8.다음 코드를 실행한 결과로 출력되는 값은?
def meet(index):
    return (index * 3 + 11 ) % 10


dat = [0 for _ in range(10)]

old = -1
start = 1
while True:
start = meet(start)
if(dat[start] == 1):
break
dat[start] = 1

if(old == start):
break

print(start)

1 . 1
2 . 2
3 . 3
4 . 4v
정답
4
해설
초기값 1부터 시작해서 meet 함수에 들렸다 나오면 3씩 증가하며, 
10이상의 값은 1의자리만 남는식으로 순회를 한다. 
최종적으로 다시 순회했던 초기값 1 + 3은 4가 출력된다

In [ ]:
9. 다음 코드를 실행한 결과로 출력되는 값은?
arr = [1, 2, 3, 1, 2, 3, 9, 6, 5]
brr = [4, 3, 5, 2, 3, 1, 9]
dat = [0 for _ in range(10)]

for i in range(len(arr)):
dat[arr[i]] = 1

for i in range(len(brr)):
dat[brr[i]] = 1

cnt = 0

for i in range(10):
cnt += dat[i]

print(cnt)

1 . 3
2 . 7 v
3 . 5
4 . 1
정답
2
해설
dat[원소 값] = 해당 원소가 있는가의 형태로 
사용하는 DAT배열로 arr과 brr에 어떤 원소들이 있는지 기록하여 
그 종류의 가짓수를 출력한다.

In [ ]:
10.
아래 코드는 matrix에서 현재 값 기준으로 네가지 방향을 ____ 순으로 출력한다.
밑줄에 알맞은 방향은 무엇인가

matrix = [[i for i in range(j*10, (j+1)*10)] for j in range(10)]

dr = [1, -1, 0, 0]
dc = [0, 0, -1, 1]

r, c = 5, 5

print(f'현재: {matrix[r][c]}')

for idx in range(4):
nr = r + dr[idx]
nc = c + dc[idx]

print(matrix[nr][nc])

1 . 상우하좌
2 . 상좌하우
3 . 하상좌우 v
4 . 상하좌우
정답
3
해설
dr 이 열번호(상하), dx가 행번호(좌우)를 의미하는 
델타값이기 때문에 하상좌우 순서가 된다.