In [ ]:
# 배열
"""
넘파이(배열)과 파이썬(리스트) 차이
파이썬(리스트)_느리고 메모리 차지하는게 많음
넘파이(배열)_빠르고 메모리 차지하는게 적음

배열 : 모든 자로형이 동일 / 데이터의 개수를 변경할 수 없다.
파이썬에서 배열을 기본적으로 제공하지 않으므로, 별도로 넘파이 패키지를 설치하여 배열을 사용

벡터 : 숫자를 원소로 갖는 리스트(배열) / 행벡터,열벡터
행벡터 _ x=[x1,x2 ... xn]
공간에서의 한 점
원점으로부너 떨어진 상대적 위치

행렬 : 벡터를 원소로 갖는 2차원 배열
공간에서의 여러 점(데이터 모임)
행렬 곱셈을 통해 백터를 다른 차원으로 공간으로 이동할 수 있음
"""
'''
#배열 만드는 방법
import numpy as np
array_x = np.array(x)
array_x # 1차원배열(벡터)

arr = np.array(list(range(1,25)))
arr #array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24]) 출력
'''

In [2]:
pip list #섩치된 목록 확인

Package                       Version
----------------------------- ------------
aiobotocore                   2.5.0
aiofiles                      22.1.0
aiohttp                       3.8.5
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
anaconda-anon-usage           0.4.2
anaconda-catalogs             0.2.0
anaconda-client               1.12.1
anaconda-cloud-auth           0.1.3
anaconda-navigator            2.5.4
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
applaunchservices             0.3.0
appnope                       0.1.2
appscript                     1.1.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asgiref                       3.8.1
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
async-timeout

service-identity              18.1.0
setuptools                    68.0.0
sip                           6.6.2
six                           1.16.0
smart-open                    5.2.1
sniffio                       1.3.1
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.4
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.3
spyder-kernels                2.4.4
SQLAlchemy                    1.4.39
sqlparse                      0.4.4
stack-data                    0.2.0
statsmodels                   0.14.0
sympy                         1.11.1
tables                        3.8.0
tabulate                      0.8.10
tblib                         1.7.0
tenacity                      8.2.2
terminado              

In [3]:
x = [10,20,30] #x의 타입은 list이고 각 하나의 의미하는 것은 int(type(x[0]))이다
type(x)

list

In [4]:
#배열 만드는 방법
import numpy as np
array_x = np.array(x)
array_x # 1차원배열(벡터)

array([10, 20, 30])

In [2]:
#array_x의 타입은 numpy.ndarray이다
type(array_x)

NameError: name 'array_x' is not defined

In [ ]:
'''
사과:1000, 딸기;2000, 배:2000, 파인애플:5000, 바나나:3000

한줄은 행백터이다. ex)5/1 하나의 행백터
5/1 사과:5 딸기:2 배:0 파인애플:0 바나나:2
5/2 사과:1 딸기:3 배:2 파인애플:3 바나나:0

5차원 벡터: 5차원 공간에 표현된 한점
[[5 2 0 0 3] ->행벡터  /  [5,2,0,0,3] ->리스트
[1 3 2 3 0]  ->행벡터
...
[...]]


덧셈, 뺄셈
[5 2 0 0 3] + [1 3 2 3 0] = [6 5 2 3 3]

'''

In [17]:
# list에서 3-6초정도 걸림
import time
s= time.time()
data=list(range(1,10000000))
ans = []
#data
for d in data:
    ans.append(d*2)
ans
e=time.time()
print(e-s)

3.5823891162872314


In [16]:
arr_data = np.array(data)
arr_data

array([      1,       2,       3, ..., 9999997, 9999998, 9999999])

In [20]:
# numpy에서는 0.1초이하 걸림 / for문을 사용 안함
s = time.time()
ans2=2*arr_data # 벡터화 연산
e=time.time()
print(e-s)

0.06753993034362793


In [19]:
ans2

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [23]:
x = [1,2]
y = [3,4]

In [24]:
x+y

[1, 2, 3, 4]

In [25]:
#요소간 덧셉
np.array(x) + np.array(y)

array([4, 6])

In [26]:
# 1~100까지 수 중에서 짝수를 even, 홀수를 odd에 저장한 다음
# 같은 위치의 요소끼리 비교하요 큰값을 출력하시오
# for문 사용

even = []
odd = []

for i in range(1, 101):
    if i % 2 == 0:
        even.append(i)
    else:
        odd.append(i)

for j in range(len(even)):
    if even[j] > odd[j]:
        print(even[j])
    else:
        print(odd[j])

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [ ]:
# 홀수와 짝수를 따로 만든 후 numpy로 각각 저장
even=[e for e in range(1,101) if e%2==0]
odd=[o for o in range(1,101) if o%2==1]
a_even=np.array(enven)
a_odd=np.array(odd)

In [ ]:
# 요소간 덧셈
a_even + a_odd

# 50과 비교
a_even>50

# 10과 같은 경우 True / 나머지느 False
a_even == 10

# & 사용
(a_even > 30) & (a_even % 5 == 0)

# 짝수 / 홀수
a_even
a_odd

# 비교하여 큰수 출력
a_even[a_even > a_odd]

In [ ]:
'''
파이썬 list보다 numpy가 빠르다.
'''

In [28]:
# numpy 버전 확인
np.__version__

'1.24.3'

In [29]:
np.array((10,20,30))

array([10, 20, 30])

In [30]:
# 0차원 배열 = 스칼라 = 배열의 각 요소 값
arr = np.array(10)
arr

array(10)

In [31]:
# 1차원뱌열 = 0차원 배열을 요소로 갖는 배열
arr = np.array([10,20,30])
arr

array([10, 20, 30])

In [35]:
# 2차원 배열 = 1차원 배열을 요소로 갖는 배열 = 행렬
arr = np.array([[10,20,30], [40,50,60]])
arr # 2행 3
len(arr) # 행열의 갯수
len(arr[0]) # 열의 갯수


3

In [39]:
# 3차원 배열 = 2차원 배열을 요소로 갖는 배열
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr
arr.ndim # ndim는 몇 차원인지 확인 가능


3

In [46]:
len(arr) #깊이
len(arr[0]) # 행
len(arr[0][0]) # 열

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [48]:
# 1~24 요소값으로 2*3*4 3차원 배열 생성

ar=np.array([[[ 1, 2, 3, 4],[ 5, 6, 7, 8],[ 9, 10, 11, 12]], 
         [[ 13, 14, 15, 16 ],[17, 18 ,19, 20 ],[21 ,22, 23, 24]]])

In [49]:
li=[[[ 1, 2, 3, 4],[ 5, 6, 7, 8],[ 9, 10, 11, 12]], 
         [[ 13, 14, 15, 16 ],[17, 18 ,19, 20 ],[21 ,22, 23, 24]]]

In [50]:
# list인 li에서는 +1를 하면 불가능하지만
# numpy인 ar는 +1 가능하다
ar+1

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [53]:
arr = np.array(list(range(1,25)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [54]:
# reshape는 원하는 배열 만들 수 있다.
arr_re = arr.reshape(2,3,4)
arr_re

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [56]:
arr_re.ndim
arr_re.shape

(2, 3, 4)

In [57]:
arr =np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [60]:
arr[0] # 1출력
arr[2]+arr[3] # 7출력
arr[-1] # 4출력

4

In [68]:
#2차원 배열 생성(2행 5열)
# 11~20까지 요서 값 저장
arr=np.array(list(range(11,21))).reshape(2,5)
arr #array([[11, 12, 13, 14, 15],
    #  [16, 17, 18, 19, 20]])     출력

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [72]:
arr[1] # array([16, 17, 18, 19, 20]) 출력
arr[-1] # array([16, 17, 18, 19, 20]) 출력
arr[-2] # array([11, 12, 13, 14, 15]) 출력

array([11, 12, 13, 14, 15])

In [70]:
# 인데싱_array indexing
arr[1][3] # 19 출력
arr[1,3] # 19 출력

19

In [74]:
# 1~12까지 요소로 초기화
# 3차원 배열 (2,2,3)
arr = np.array(list(range(1,13))).reshape(2,2,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
# 인데싱_array indexing
arr[0,1,2] # 6출력

6

In [76]:
# array indexing
# array slicing => 밑 2줄
# [시작:끝]
# [시작:끝:간격]

In [77]:
arr=np.array(list(range(1,8)))
arr

array([1, 2, 3, 4, 5, 6, 7])

In [82]:
arr[1] # indexing /2 출력
arr[1:5] # 시작위치 포함, 끝위치 불포함 / array([2, 3, 4, 5]) 출력
arr[3:] # array([4, 5, 6, 7]) 출력
arr[:3] # array([1, 2, 3]) 출력

array([1, 2, 3])

In [87]:
arr[-3:] # array([5, 6, 7]) 출력
arr[-5:] # array([3, 4, 5, 6, 7]) 출력
arr[-5:-2] # array([3, 4, 5]) 출력
arr[1:5:2] # array([2, 4]) 출력


array([1, 2, 3, 4, 5, 6, 7])

In [88]:
arr[:] # array([1, 2, 3, 4, 5, 6, 7])출력
arr[::] # array([1, 2, 3, 4, 5, 6, 7]) 출력
arr[::1] # array([1, 2, 3, 4, 5, 6, 7]) 출력
         #[시작:끝:스텝] 스텝을 생략하면 기본값으로 1씩 증가

array([1, 2, 3, 4, 5, 6, 7])

In [90]:
arr[::2] # array([1, 3, 5, 7]) 출력
         #[시작:끝:스텝] 스텝을 생략하면 기본값으로 2씩 증가

array([1, 3, 5, 7])

In [91]:
arr=np.array(list(range(1,11))).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [93]:
arr[1,0] # 6출력
arr[1,1:4] #array([7, 8, 9])

array([7, 8, 9])

In [94]:
arr=np.array(list(range(11,41))).reshape(6,5)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [97]:
arr[4,3]

34

In [98]:
arr[2,0:3]

array([21, 22, 23])

In [103]:
arr[1:3,1:4] # 1번부터 2번까지 행 :1번부터 3번까지 열 출력
             # array([[17, 18, 19],
             #        [22, 23, 24]]) 출력

array([[17, 18, 19],
       [22, 23, 24]])

In [105]:
pip install -U finance-datareader

  Obtaining dependency information for finance-datareader from https://files.pythonhosted.org/packages/e3/15/724a966c42658a7640813f94650d2f18e24e78ac353765762da82b86fb96/finance_datareader-0.9.90-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.6/46.6 kB 780.5 kB/s eta 0:00:000:00:01
Note: you may need to restart the kernel to use updated packages.


In [15]:
kakao_arr =np.loadtxt("kakao_pre.csv", skiprows=1, dtype=np.float32, delimiter=",")

In [16]:
kakao_arr[:5]

array([[  58000.   ,   58900.   ,   57800.   ,   58300.   ,   58237.387,
        1047114.   ],
       [  57200.   ,   57500.   ,   56000.   ,   57200.   ,   57138.57 ,
        2288474.   ],
       [  57500.   ,   58200.   ,   57100.   ,   57700.   ,   57638.03 ,
        1821528.   ],
       [  57800.   ,   58700.   ,   57300.   ,   57500.   ,   57438.246,
        1412568.   ],
       [  57100.   ,   57300.   ,   56300.   ,   56500.   ,   56439.32 ,
        1364811.   ]], dtype=float32)

In [ ]:
import numpy as np

In [5]:
# 001 넘파이를 사용하여 다음과 같은 행렬을 만든다.
#10 20 30 40
#50 60 70 80

arr=np.array(list(range(0,15))).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
# 002 다음 행렬과 같은 행렬이 있다.
arr = np.array([[ 0,  1,  2,  3,  4],
           [ 5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14]])
#이 행렬에서 값 7 을 인덱싱한다.
arr[1,2]
#이 행렬에서 값 14 을 인덱싱한다.
arr[-1,-1]
#이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
arr[1,1:3]
#이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
arr[1: ,2]
#이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
arr[:2,3:]

array([ 7, 12])

In [39]:
# 003. 값이 10에서 49를 원소로 가지고 있는 벡터 만들기
arr = np.arange(10,50)
arr
# 004. 3번 배열의 원소를 뒤집어 출력
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [43]:
#005삼성전자 주가 데이터 다운로드
# -날짜 열 제거
# -시가, 종가, 고가, 저가, 거래량을 각각 추출
# -2024년 5월 1일~ 5월 3일까지 데이터만 추출
samsung_arr =np.loadtxt("samsung_pre.csv", skiprows=1, dtype=np.float32, delimiter=",")

#시가
samsung_arr[-2,0]
#종가
samsung_arr[-2,3]
#고가
samsung_arr[-2,1]
#저가
samsung_arr[-2,2]
#거래량
samsung_arr[-2,-1]
#2024년 5월 1일~ 5월 3일까지 데이터만 추출
samsung_arr[-3:,:]

In [53]:
#시가
samsung_arr[-2,0]
#종가
samsung_arr[-2,3]
#고가
samsung_arr[-2,1]
#저가
samsung_arr[-2,2]
#거래량
samsung_arr[-2,-1]
#2024년 5월 1일~ 5월 3일까지 데이터만 추출
samsung_arr[-3:,:]

18900640.0

In [57]:
samsung_arr[-3:,:]

array([[   77000.,    78500.,    76600.,    77500.,    77500., 19007008.],
       [   77600.,    78600.,    77300.,    78000.,    78000., 18900640.],
       [   79000.,    79000.,    77500.,    77700.,    77700., 12165808.]],
      dtype=float32)

In [ ]:
arr[1:3,1:4] # 1번부터 2번까지 행 :1번부터 3번까지 열 출력